<h2 style="text-align: center;"> VALIDACIÓN HOLD OUT </h2>

<img src="img/ITQ.jpg" width="800">

**Nombre:** *Sebastian Sampedro* <br>
**Fecha:** *11/5/2026* <br>
**Link Github:** "https://github.com/sdsampedro-byte/Python2026ML"

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# Carga de datos
iris = datasets.load_iris()
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [3]:
# Mostrar características de la tabla de datos.
print("Tabla de datos: %d instancias y %d atributos" % (iris.data.shape[0], iris.data.shape[1]))
print("Valores de la clase:", set(iris.target))

# Cuantificamos el número de instancias que contiene el dataset por clase
valores, ocurrencias = np.unique(iris.target, return_counts=True)
print(valores, ocurrencias)

Tabla de datos: 150 instancias y 4 atributos
Valores de la clase: {np.int64(0), np.int64(1), np.int64(2)}
[0 1 2] [50 50 50]


In [4]:
# Test: hold-out split 80-20%. # Partición externa
X_training, X_test, y_training, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
valores_test, ocur_test = np.unique(y_test, return_counts=True)
print('Test: ', 'clases:', valores_test, ' ocurrencias: ', ocur_test)

Test:  clases: [0 1 2]  ocurrencias:  [10  9 11]


In [5]:
# Estandarizar las características de entrenamiento y de test
standardizer = StandardScaler()
X_training = standardizer.fit_transform(X_training)
X_test = standardizer.transform(X_test)

In [6]:
# Validación: hold-out split 80-20%. # Partición interna
X_train, X_val, y_train, y_val = train_test_split(X_training, y_training, test_size=0.2, random_state=42)
valores_train, ocur_train = np.unique(y_train, return_counts=True)
print('Entrenamiento: ', ' clases:', valores_train, '  ocurrencias:', ocur_train)

valores_val, ocur_val = np.unique(y_val, return_counts=True)
print('Validation:    ', ' clases:', valores_val, '  ocurrencias:', ocur_val)

Entrenamiento:   clases: [0 1 2]   ocurrencias: [32 30 34]
Validation:      clases: [0 1 2]   ocurrencias: [ 8 11  5]


In [7]:
# Construcción del objeto que contiene el algoritmo de aprendizaje.
clf = DummyClassifier(strategy='prior', random_state=42)

In [8]:
# Entrenamiento del algoritmo de aprendizaje.
clf = clf.fit(X_train, y_train)

In [9]:
# Evaluación del algoritmo de aprendizaje con el método "score" que devuelve directamente la métrica de 'accuracy'
val_accuracy = clf.score(X_val, y_val)
print("Exactitud en validación: ", val_accuracy)

test_accuracy = clf.score(X_test, y_test)
print("Exactitud en test: ", test_accuracy)

Exactitud en validación:  0.20833333333333334
Exactitud en test:  0.36666666666666664


In [10]:
# Obtenemos las predicciones sobre conjunto de validación y de test
y_pred_val = clf.predict(X_val)
print('Predicciones de validación ', y_pred_val)
print('Etiquetas reales validación', y_val)

y_pred_test = clf.predict(X_test)
print('\nPredicciones de test ', y_pred_val)
print('Etiquetas reales test', y_val)

Predicciones de validación  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
Etiquetas reales validación [1 1 0 0 0 2 1 2 2 2 1 1 1 1 1 0 2 0 1 0 1 1 0 0]

Predicciones de test  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
Etiquetas reales test [1 1 0 0 0 2 1 2 2 2 1 1 1 1 1 0 2 0 1 0 1 1 0 0]


In [11]:
# Aplicamos un ejemplo con un clasificador más complejo que el "dummyclassifier"
from sklearn.svm import SVC
svc = SVC(C=0.5) # Definimos algoritmo
svc.fit(X_train, y_train) # Entrenamos modelo

val_accuracy = svc.score(X_val, y_val) # Evaluamos modelo en validación
print('Exactitud en validación ', np.round(val_accuracy*100, 4), '%')

test_accuracy = svc.score(X_test, y_test) # Evaluamos modelo en test
print('Exactitud en test ', np.round(test_accuracy*100, 4), '%')

Exactitud en validación  91.6667 %
Exactitud en test  96.6667 %


In [12]:
# Guardar modelo
import pickle
with open('models/model.pickle', 'wb') as fw:
    pickle.dump(svc, fw)

# Cargar modelo
with open('models/model.pickle', 'rb') as fr:
    modelo=pickle.load(fr)
print("Modelo cargado")

# Guardamos el escalado 
with open('models/scaler.pkl','wb') as fw:
    pickle.dump(standardizer, fw)

# Cargamos el Scaler
with open('models/scaler.pkl','rb') as f:
    scaler_cargado = pickle.load(f)

print("Modelo y Scaler cargados")

Modelo cargado
Modelo y Scaler cargados


In [15]:
# Nuevos datos
nuevo_dato=[[5.1, 3.5, 1.4, 0.2]]
# Escalo datos
nuevo_dato_escalado = scaler_cargado.transform(nuevo_dato)
print(nuevo_dato_escalado)

[[-0.86445224  0.98006827 -1.33331205 -1.31260282]]


In [19]:
# Predicción
prediccion=modelo.predict(nuevo_dato_escalado)
print(prediccion)

[0]


In [29]:
# Mostrar ¿Qué tipo de rosa es?
prediccion=modelo.predict(nuevo_dato_escalado)
print(prediccion)
if prediccion==0:
    print("La flor que se predijo es", 0, "Setosa")
elif prediccion==1:
    print("La flor que se predijo es", 1,"Versicolor")
else:
     print("La flor que se predijo es", 2,"virginica")

[0]
La flor que se predijo es 0 Setosa


In [13]:
# Ingresar datos por teclado
tamaño_sepalo = float(input("Ingrese el tamaño del sépalo: "))
anchura_sepalo = float(input("Ingrese la anchura del sépalo: "))
tamaño_petalo = float(input("Ingrese el tamaño del pétalo: "))
anchura_petalo = float(input("Ingrese la anchura del pétalo: "))

# Crear arreglo con los datos ingresados
nuevo_dato1 = [[tamaño_sepalo, anchura_sepalo, tamaño_petalo, anchura_petalo]]

# Escalar datos
nuevo_dato_escalado1 = scaler_cargado.transform(nuevo_dato1)

print("Datos escalados:")
print(nuevo_dato_escalado1)

Ingrese el tamaño del sépalo:  1
Ingrese la anchura del sépalo:  2
Ingrese el tamaño del pétalo:  3
Ingrese la anchura del pétalo:  4


Datos escalados:
[[-5.8622255  -2.37377751 -0.41642124  3.75982841]]


In [16]:
prediccion=modelo.predict(nuevo_dato_escalado1)
print(prediccion)
if prediccion==0:
    print("La flor que se predijo es", 0, "Setosa")
elif prediccion==1:
    print("La flor que se predijo es", 1,"Versicolor")
else:
     print("La flor que se predijo es", 2,"virginica")

[2]
La flor que se predijo es 2 virginica
