<h2 style="text-align: center;"> ESTANDARIZACIÓN </h2>

<img src="img/ITQ.jpg" width="700">

**Nombre:** *Sebastian Sampedro* <br>
**Link Github:** "https://github.com/sdsampedro-byte/Python2026ML"

In [6]:
from sklearn import preprocessing
import numpy as np

In [7]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [8]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [9]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [10]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)


[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
# Comprobar si las matrices estandarizadas son iguales

print(np.array_equiv(X_train, X_train_2_std))

True
